const seedSignals = [
  {
    id: "sig-1001",
    date: "2026-02-06",
    source: "Scholar 1:1",
    theme: "Belonging",
    sentiment: 1.5,
    urgency: "medium",
    response_due: false,
    notes: "Scholar felt more connected after cohort circle, wants more peer pods.",
  },
  {
    id: "sig-1002",
    date: "2026-02-06",
    source: "Survey Pulse",
    theme: "Financial Stress",
    sentiment: -1.5,
    urgency: "high",
    response_due: true,
    notes: "Unexpected textbook costs driving anxiety; asks for emergency support update.",
  },
  {
    id: "sig-1003",
    date: "2026-02-05",
    source: "Group Session",
    theme: "Career Readiness",
    sentiment: 0.5,
    urgency: "medium",
    response_due: false,
    notes: "Cohort wants more mock interview reps before March recruiting push.",
  },
  {
    id: "sig-1004",
    date: "2026-02-05",
    source: "Partner Check-in",
    theme: "Program Clarity",
    sentiment: -0.5,
    urgency: "high",
    response_due: true,
    notes: "Partner asked for clearer scholar milestones and progress updates.",
  },
  {
    id: "sig-1005",
    date: "2026-02-04",
    source: "Mentor Office Hours",
    theme: "Community Energy",
    sentiment: 1,
    urgency: "low",
    response_due: false,
    notes: "Mentors report strong energy; requested bi-weekly highlight email.",
  },
];
